# Generated by Django 3.0.6 on 2020-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('aadhar', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('flat_no', models.SmallIntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbldata',
            },
        ),
    ]
