# Generated by Django 3.0.6 on 2020-10-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assapp', '0002_tbldata_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldata',
            name='aadhar',
        ),
    ]
