# Generated by Django 3.0.6 on 2020-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assapp', '0003_remove_tbldata_aadhar'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblvdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbldata_id', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=10)),
                ('no_of_time', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tblvdetails',
            },
        ),
    ]
